stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wenteng/springtest
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
